[package]
name = "cherryusb-rs-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.69"
cc = "1.0"
glob = "0.3"

[features]
default = ["device", "ohci"]
# Mode
host = []
device = []
# IP Cores
ehci = []
dwc2 = []
fsdev = []
musb = []
ohci = ["ehci"]


